spring:
  boot:
    admin:
      client:
        url: http://localhost:9091
  application:
    name: taco-cloud
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rsocket
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    template:
      receive-timeout: 30000
  kafka:
    bootstrap-servers:
      localhost:9093
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile




