spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <facebook client id>
            clientSecret: <facebook client secret>
            scope: email, public_profile


